# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .has_default import *
from .no_default import *
from .provider import *
from ._inputs import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "nested",
  "mod": "index",
  "fqn": "pulumi_nested",
  "classes": {
   "nested:index:HasDefault": "HasDefault",
   "nested:index:NoDefault": "NoDefault"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "nested",
  "token": "pulumi:providers:nested",
  "fqn": "pulumi_nested",
  "class": "Provider"
 }
]
"""
)
