# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: nested
types:
  "nested:index:NestedHasDefault":
    type: "object"
    properties:
      value:
        type: string
        default: ""
  "nested:index:NestedNoDefault":
    type: "object"
    properties:
      value:
        type: string
resources:
  nested:index:NoDefault:
    isComponent: true
    inputProperties:
      value:
        type: string
      nested:
        $ref: "#/types/nested:index:NestedNoDefault"
    requiredInputs: []
    properties:
      value:
        type: string
    required:
      - value
  nested:index:HasDefault:
    isComponent: true
    inputProperties:
      value:
        type: string
      nested:
        $ref: "#/types/nested:index:NestedHasDefault"
    requiredInputs: []
    properties:
      value:
        type: string
    required:
      - value
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/pulumi/pulumi-nested/sdk/go/nested
  nodejs:
    dependencies:
      "@pulumi/pulumi": "^3.0.0"
    devDependencies:
      typescript: "^3.7.0"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
