// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nested
{
    [NestedResourceType("nested:index:HasDefault")]
    public partial class HasDefault : global::Pulumi.ComponentResource
    {
        [Output("value")]
        public Output<string> Value { get; private set; } = null!;


        /// <summary>
        /// Create a HasDefault resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public HasDefault(string name, HasDefaultArgs? args = null, ComponentResourceOptions? options = null)
            : base("nested:index:HasDefault", name, args ?? new HasDefaultArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class HasDefaultArgs : global::Pulumi.ResourceArgs
    {
        [Input("nested")]
        public Input<Inputs.NestedHasDefaultArgs>? Nested { get; set; }

        [Input("value")]
        public Input<string>? Value { get; set; }

        public HasDefaultArgs()
        {
        }
        public static new HasDefaultArgs Empty => new HasDefaultArgs();
    }
}
