// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nested

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NestedHasDefault struct {
	Value *string `pulumi:"value"`
}

// Defaults sets the appropriate defaults for NestedHasDefault
func (val *NestedHasDefault) Defaults() *NestedHasDefault {
	if val == nil {
		return nil
	}
	tmp := *val
	if isZero(tmp.Value) {
		value_ := ""
		tmp.Value = &value_
	}
	return &tmp
}

// NestedHasDefaultInput is an input type that accepts NestedHasDefaultArgs and NestedHasDefaultOutput values.
// You can construct a concrete instance of `NestedHasDefaultInput` via:
//
//	NestedHasDefaultArgs{...}
type NestedHasDefaultInput interface {
	pulumi.Input

	ToNestedHasDefaultOutput() NestedHasDefaultOutput
	ToNestedHasDefaultOutputWithContext(context.Context) NestedHasDefaultOutput
}

type NestedHasDefaultArgs struct {
	Value pulumi.StringPtrInput `pulumi:"value"`
}

// Defaults sets the appropriate defaults for NestedHasDefaultArgs
func (val *NestedHasDefaultArgs) Defaults() *NestedHasDefaultArgs {
	if val == nil {
		return nil
	}
	tmp := *val
	if isZero(tmp.Value) {
		tmp.Value = pulumi.StringPtr("")
	}
	return &tmp
}
func (NestedHasDefaultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*NestedHasDefault)(nil)).Elem()
}

func (i NestedHasDefaultArgs) ToNestedHasDefaultOutput() NestedHasDefaultOutput {
	return i.ToNestedHasDefaultOutputWithContext(context.Background())
}

func (i NestedHasDefaultArgs) ToNestedHasDefaultOutputWithContext(ctx context.Context) NestedHasDefaultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NestedHasDefaultOutput)
}

func (i NestedHasDefaultArgs) ToNestedHasDefaultPtrOutput() NestedHasDefaultPtrOutput {
	return i.ToNestedHasDefaultPtrOutputWithContext(context.Background())
}

func (i NestedHasDefaultArgs) ToNestedHasDefaultPtrOutputWithContext(ctx context.Context) NestedHasDefaultPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NestedHasDefaultOutput).ToNestedHasDefaultPtrOutputWithContext(ctx)
}

// NestedHasDefaultPtrInput is an input type that accepts NestedHasDefaultArgs, NestedHasDefaultPtr and NestedHasDefaultPtrOutput values.
// You can construct a concrete instance of `NestedHasDefaultPtrInput` via:
//
//	        NestedHasDefaultArgs{...}
//
//	or:
//
//	        nil
type NestedHasDefaultPtrInput interface {
	pulumi.Input

	ToNestedHasDefaultPtrOutput() NestedHasDefaultPtrOutput
	ToNestedHasDefaultPtrOutputWithContext(context.Context) NestedHasDefaultPtrOutput
}

type nestedHasDefaultPtrType NestedHasDefaultArgs

func NestedHasDefaultPtr(v *NestedHasDefaultArgs) NestedHasDefaultPtrInput {
	return (*nestedHasDefaultPtrType)(v)
}

func (*nestedHasDefaultPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**NestedHasDefault)(nil)).Elem()
}

func (i *nestedHasDefaultPtrType) ToNestedHasDefaultPtrOutput() NestedHasDefaultPtrOutput {
	return i.ToNestedHasDefaultPtrOutputWithContext(context.Background())
}

func (i *nestedHasDefaultPtrType) ToNestedHasDefaultPtrOutputWithContext(ctx context.Context) NestedHasDefaultPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NestedHasDefaultPtrOutput)
}

type NestedHasDefaultOutput struct{ *pulumi.OutputState }

func (NestedHasDefaultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NestedHasDefault)(nil)).Elem()
}

func (o NestedHasDefaultOutput) ToNestedHasDefaultOutput() NestedHasDefaultOutput {
	return o
}

func (o NestedHasDefaultOutput) ToNestedHasDefaultOutputWithContext(ctx context.Context) NestedHasDefaultOutput {
	return o
}

func (o NestedHasDefaultOutput) ToNestedHasDefaultPtrOutput() NestedHasDefaultPtrOutput {
	return o.ToNestedHasDefaultPtrOutputWithContext(context.Background())
}

func (o NestedHasDefaultOutput) ToNestedHasDefaultPtrOutputWithContext(ctx context.Context) NestedHasDefaultPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v NestedHasDefault) *NestedHasDefault {
		return &v
	}).(NestedHasDefaultPtrOutput)
}

func (o NestedHasDefaultOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v NestedHasDefault) *string { return v.Value }).(pulumi.StringPtrOutput)
}

type NestedHasDefaultPtrOutput struct{ *pulumi.OutputState }

func (NestedHasDefaultPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NestedHasDefault)(nil)).Elem()
}

func (o NestedHasDefaultPtrOutput) ToNestedHasDefaultPtrOutput() NestedHasDefaultPtrOutput {
	return o
}

func (o NestedHasDefaultPtrOutput) ToNestedHasDefaultPtrOutputWithContext(ctx context.Context) NestedHasDefaultPtrOutput {
	return o
}

func (o NestedHasDefaultPtrOutput) Elem() NestedHasDefaultOutput {
	return o.ApplyT(func(v *NestedHasDefault) NestedHasDefault {
		if v != nil {
			return *v
		}
		var ret NestedHasDefault
		return ret
	}).(NestedHasDefaultOutput)
}

func (o NestedHasDefaultPtrOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NestedHasDefault) *string {
		if v == nil {
			return nil
		}
		return v.Value
	}).(pulumi.StringPtrOutput)
}

type NestedNoDefault struct {
	Value *string `pulumi:"value"`
}

// NestedNoDefaultInput is an input type that accepts NestedNoDefaultArgs and NestedNoDefaultOutput values.
// You can construct a concrete instance of `NestedNoDefaultInput` via:
//
//	NestedNoDefaultArgs{...}
type NestedNoDefaultInput interface {
	pulumi.Input

	ToNestedNoDefaultOutput() NestedNoDefaultOutput
	ToNestedNoDefaultOutputWithContext(context.Context) NestedNoDefaultOutput
}

type NestedNoDefaultArgs struct {
	Value pulumi.StringPtrInput `pulumi:"value"`
}

func (NestedNoDefaultArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*NestedNoDefault)(nil)).Elem()
}

func (i NestedNoDefaultArgs) ToNestedNoDefaultOutput() NestedNoDefaultOutput {
	return i.ToNestedNoDefaultOutputWithContext(context.Background())
}

func (i NestedNoDefaultArgs) ToNestedNoDefaultOutputWithContext(ctx context.Context) NestedNoDefaultOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NestedNoDefaultOutput)
}

func (i NestedNoDefaultArgs) ToNestedNoDefaultPtrOutput() NestedNoDefaultPtrOutput {
	return i.ToNestedNoDefaultPtrOutputWithContext(context.Background())
}

func (i NestedNoDefaultArgs) ToNestedNoDefaultPtrOutputWithContext(ctx context.Context) NestedNoDefaultPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NestedNoDefaultOutput).ToNestedNoDefaultPtrOutputWithContext(ctx)
}

// NestedNoDefaultPtrInput is an input type that accepts NestedNoDefaultArgs, NestedNoDefaultPtr and NestedNoDefaultPtrOutput values.
// You can construct a concrete instance of `NestedNoDefaultPtrInput` via:
//
//	        NestedNoDefaultArgs{...}
//
//	or:
//
//	        nil
type NestedNoDefaultPtrInput interface {
	pulumi.Input

	ToNestedNoDefaultPtrOutput() NestedNoDefaultPtrOutput
	ToNestedNoDefaultPtrOutputWithContext(context.Context) NestedNoDefaultPtrOutput
}

type nestedNoDefaultPtrType NestedNoDefaultArgs

func NestedNoDefaultPtr(v *NestedNoDefaultArgs) NestedNoDefaultPtrInput {
	return (*nestedNoDefaultPtrType)(v)
}

func (*nestedNoDefaultPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**NestedNoDefault)(nil)).Elem()
}

func (i *nestedNoDefaultPtrType) ToNestedNoDefaultPtrOutput() NestedNoDefaultPtrOutput {
	return i.ToNestedNoDefaultPtrOutputWithContext(context.Background())
}

func (i *nestedNoDefaultPtrType) ToNestedNoDefaultPtrOutputWithContext(ctx context.Context) NestedNoDefaultPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NestedNoDefaultPtrOutput)
}

type NestedNoDefaultOutput struct{ *pulumi.OutputState }

func (NestedNoDefaultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*NestedNoDefault)(nil)).Elem()
}

func (o NestedNoDefaultOutput) ToNestedNoDefaultOutput() NestedNoDefaultOutput {
	return o
}

func (o NestedNoDefaultOutput) ToNestedNoDefaultOutputWithContext(ctx context.Context) NestedNoDefaultOutput {
	return o
}

func (o NestedNoDefaultOutput) ToNestedNoDefaultPtrOutput() NestedNoDefaultPtrOutput {
	return o.ToNestedNoDefaultPtrOutputWithContext(context.Background())
}

func (o NestedNoDefaultOutput) ToNestedNoDefaultPtrOutputWithContext(ctx context.Context) NestedNoDefaultPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v NestedNoDefault) *NestedNoDefault {
		return &v
	}).(NestedNoDefaultPtrOutput)
}

func (o NestedNoDefaultOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v NestedNoDefault) *string { return v.Value }).(pulumi.StringPtrOutput)
}

type NestedNoDefaultPtrOutput struct{ *pulumi.OutputState }

func (NestedNoDefaultPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NestedNoDefault)(nil)).Elem()
}

func (o NestedNoDefaultPtrOutput) ToNestedNoDefaultPtrOutput() NestedNoDefaultPtrOutput {
	return o
}

func (o NestedNoDefaultPtrOutput) ToNestedNoDefaultPtrOutputWithContext(ctx context.Context) NestedNoDefaultPtrOutput {
	return o
}

func (o NestedNoDefaultPtrOutput) Elem() NestedNoDefaultOutput {
	return o.ApplyT(func(v *NestedNoDefault) NestedNoDefault {
		if v != nil {
			return *v
		}
		var ret NestedNoDefault
		return ret
	}).(NestedNoDefaultOutput)
}

func (o NestedNoDefaultPtrOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NestedNoDefault) *string {
		if v == nil {
			return nil
		}
		return v.Value
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NestedHasDefaultInput)(nil)).Elem(), NestedHasDefaultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*NestedHasDefaultPtrInput)(nil)).Elem(), NestedHasDefaultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*NestedNoDefaultInput)(nil)).Elem(), NestedNoDefaultArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*NestedNoDefaultPtrInput)(nil)).Elem(), NestedNoDefaultArgs{})
	pulumi.RegisterOutputType(NestedHasDefaultOutput{})
	pulumi.RegisterOutputType(NestedHasDefaultPtrOutput{})
	pulumi.RegisterOutputType(NestedNoDefaultOutput{})
	pulumi.RegisterOutputType(NestedNoDefaultPtrOutput{})
}
