// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

export interface NestedHasDefaultArgs {
    value?: pulumi.Input<string>;
}
/**
 * nestedHasDefaultArgsProvideDefaults sets the appropriate defaults for NestedHasDefaultArgs
 */
export function nestedHasDefaultArgsProvideDefaults(val: NestedHasDefaultArgs): NestedHasDefaultArgs {
    return {
        ...val,
        value: (val.value) ?? "",
    };
}

export interface NestedNoDefaultArgs {
    value?: pulumi.Input<string>;
}
