// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Nested.Inputs
{

    public sealed class NestedNoDefaultArgs : global::Pulumi.ResourceArgs
    {
        [Input("value")]
        public Input<string>? Value { get; set; }

        public NestedNoDefaultArgs()
        {
        }
        public static new NestedNoDefaultArgs Empty => new NestedNoDefaultArgs();
    }
}
