// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class NoDefault extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'nested:index:NoDefault';

    /**
     * Returns true if the given object is an instance of NoDefault.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NoDefault {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NoDefault.__pulumiType;
    }

    public readonly value!: pulumi.Output<string>;

    /**
     * Create a NoDefault resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NoDefaultArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["nested"] = args ? args.nested : undefined;
            resourceInputs["value"] = args ? args.value : undefined;
        } else {
            resourceInputs["value"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NoDefault.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a NoDefault resource.
 */
export interface NoDefaultArgs {
    nested?: pulumi.Input<inputs.NestedNoDefaultArgs>;
    value?: pulumi.Input<string>;
}
